---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  reloader.stakater.com/auto: "true"
  customer: "underwriteme"
  region: "eu-west0-a"
  environment: "local"
  team: "local"
  spring-profile: "default"
commonLabels:
  app_name: "config-server"
  app_version: "0.1"
  maintained_by: "underwriteme"
  app.kubernetes.io/name: "config-server"
  app.kubernetes.io/instance: "config-server"
resources:
- manifest/deploy.yml
- manifest/rbac.yml
- manifest/svc.yml
