spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leangeder/config-files.git
          defaultLabel: main
          pattern: "{application}/{profile}"
          searchPaths:
          # - ${TEAM}/${ENVIRONMENT}/{application}/{profile}
          - ${TEAM}/{application}
          - ${TEAM}/{application}/${ENVIRONMENT}
          - ${TEAM}/{application}/${ENVIRONMENT}/${REGION}
server:
  port: 8080
